### ISSUE TITLE
@Recovery method not found for ParameterizedType

### ISSUE THREAD

**Issue by MahatmaFatalError** [spring-projects/spring-retry#364] opened 2023-06-16 13:54 UTC
Given the following example

```java
	@Retryable(
			retryFor = {ResourceAccessException.class },
			recover = "raiseExceptionAfterMaxAttemptsExceeded",
			maxAttemptsExpression = "${integration.maxAttempts}",
			backoff = @Backoff(delayExpression = "${integration.backoffDelay}"))
	public <RES, REQ> ResponseEntity<RES> exchange(final String extension, final HttpMethod method, final REQ request,
			final HttpHeaders headers, final Class<RES> responseType, final String... pathSegments) {
		final URI uri = this.buildUrl(extension, pathSegments);
		return this.restTemplate.exchange(uri, method, new HttpEntity<>(request, headers), responseType);
	}

	/**
	 * Try to recover from failures related to I/O exceptions after retrying calls. In our case, wrap exception with
	 * custom exception. The return type needs to be the same as the retryable method. (return not used)
	 */
	@Recover
	public <RES> ResponseEntity<RES> raiseExceptionAfterMaxAttemptsExceeded(final ResourceAccessException exception) {
		throw this.myErrorHandler.mapIOException(exception);
	}
```

This snipped used to work with Spring Boot 2.7 and Retry 1 (with `value` instead of `retryFor` and w/o explicit `recover`), now with Spring Boot 3.1 and Retry 2.0.1 it does not work anymore.

Basically, the recovery method is not found anymore
```
org.springframework.retry.ExhaustedRetryException: Cannot locate recovery method
	at org.springframework.retry.annotation.RecoverAnnotationRecoveryHandler.recover(RecoverAnnotationRecoveryHandler.java:77)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor$ItemRecovererCallback.recover(RetryOperationsInterceptor.java:159)
	at org.springframework.retry.support.RetryTemplate.handleRetryExhausted(RetryTemplate.java:543)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:389)
	at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:225)
	at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:124)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:160)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:702)
```

I tried to set `proxyTargetClass = true` on `@EnableRetry` but this does not solve the issue.

I debugged a bit and I found that `RecoverAnnotationRecoveryHandler.init()` never reaches `putToMethodsMap` because `isParameterizedTypeAssignable((ParameterizedType) candidate.getGenericReturnType(), (ParameterizedType) failingMethod.getGenericReturnType())` returns `false`.
![image](https://github.com/spring-projects/spring-retry/assets/776825/0fda87a3-663b-4d18-853c-0bdc3960ab01)

**Comment by artembilan** [comment] 2023-06-16 14:28
I believe the previous version didn't take into account a generic argument of the return type. 
Now it consults over there as well, but looks like that `ResponseEntity<RES>` is a placeholder and we don't take it into account in the `isParameterizedTypeAssignable()` logic.

Does it make sense?
If you see some fix, feel free to contribute it.

I don't see an easy workaround for you unless you pull those retryable methods to the class with specific generic argument...

**Comment by MahatmaFatalError** [comment] 2023-06-16 14:44
Wouldn't it be enough to compare only the type names if they are in the same class?

**Comment by artembilan** [comment] 2023-06-16 14:49
Probably. didn't look into code yet: busy with other stuff.

as I said: feel free to open Pull Request and we will review together.

Thank you!

**Comment by artembilan** [comment] 2023-06-16 19:46
So, this one works:
```
	public static class MyGenericService<T> {

		@Retryable(retryFor = IllegalArgumentException.class)
		public Optional<T> retryMe(T retry) {
			throw new IllegalArgumentException("for retry");
		}

		@Recover
		public Optional<T> recoverForRetry() {
			return Optional.empty();
		}

	}
```

I believe your configuration is not supposed to work because those type parameters in those methods are really different things, even if they have the same name:
```
<RES, REQ> ResponseEntity<RES>

<RES> ResponseEntity<RES>
```
That `RES` has no connection from one method to another from language definition perspective for this structures.

If you really want to have some meaning with that generic type and really have it connected between those two methods, then move it to the class as I have in my sample.

Closing this as `Works as Designed`.

**Closed by artembilan** 2023-06-16 19:46 UTC
