### ISSUE TITLE
@Retryable annotated method retries maxAttempts*maxAttempts times

### ISSUE THREAD

**Issue by kpodkalicki** [spring-projects/spring-retry#466] opened 2024-09-06 16:32 UTC
Hi there 🙂 

I'm having this issue where a method annotated with `@Retryable` will retry `maxAttempts`*`maxAttempts` times.

A simplified code example:
```java
public interface TestService {
    String doStuff();
}

@Component
public class TestServiceImpl implements TestService {
    
    @Retryable(maxAttempts = 4)
    public String doStuff() {
        System.out.println("doing stuff, retryContext: " + RetrySynchronizationManager.getContext());
        throw new RuntimeException();
    }
}

@Configuration(proxyBeanMethods = false)
@EnableRetry
public class TestConfig {

    @Primary
    @Bean
    public TestService testService(TestServiceImpl impl) {
        return impl;
    }
}

@RestController
public class TestController {
    private final TestService testService;

    public TestController(TestService testService) {
        this.testService = testService;
    }

    @GetMapping("/test")
    public ResponseEntity<?> test() {
        return ResponseEntity.ok(testService.doStuff());
    }
}
```
Whenever I call the `/test` endpoint the `doing stuff, retryContext: ...` message gets logged 16 times (instead of expected 4). My debugger shows that the `TestService` instance that gets autowired into the `TestController` is in fact a proxy of a proxy of `TestServiceImpl`.
Changing the signature of `TestController`'s constructor to `TestController(TestServiceImpl testService)` resolves this issue. 

Is it possible to get around this problem without changing how the beans are created? In my real code that `@Bean` annotated method is a little bit more complex as it has to select one of the existing implementations based on some conditions.

Versions used:
- `spring-aop:6.1.5`
- `spring-retry:2.0.5`

Best regards!

**Comment by artembilan** [comment] 2024-09-06 16:36
Hi, @kpodkalicki !

A simple project to reproduce would be great.
However I don't see we really need a REST controller to test this stuff.

Thanks

**Comment by artembilan** [comment] 2024-09-06 18:24
I think I see what is the problem.
You have two beans pointing to the same object:
```
@Component
public class TestServiceImpl implements TestService {
```
and then:
```
    @Primary
    @Bean
    public TestService testService(TestServiceImpl impl) {
        return impl;
    }
```

The Spring Retry annotation parser goes over both of those beans registering respective `AnnotationAwareRetryOperationsInterceptor` for those bean via `AnnotationAwareAspectJAutoProxyCreator`.
Essentially making a double proxy for the original object.
So, when you call `testService.doStuff();` on your `@Primary` bean, it is going through retry for every internal retry cycle failures.  

Nothing wrong from the framework perspective.
Looks like a misconfiguration in the target project.

Closing as `Works as Designed`.

**Closed by artembilan** 2024-09-06 18:24 UTC
