### ISSUE TITLE
RetryListenerSupport#onError  is  trigger with an unexpected Exception

### ISSUE THREAD

**Issue by lianyiwuming** [spring-projects/spring-retry#337] opened 2023-04-20 10:11 UTC
I expect retry on exception type ZabbixAuthException，but got  RetryListenerSupport#onError invoked by exception type RuntimeException. 
![Uploading 1ac47ab403c0982d61477e30519865e.png…]()

**Comment by snicoll** [comment] 2023-04-20 12:11
Duplicate of #338

**Closed by snicoll** 2023-04-20 12:11 UTC
