### ISSUE TITLE
Nullpointer if host name has underscores

### ISSUE THREAD

**Issue by bijanfahimi** [spring-projects/spring-retry#107] opened 2018-02-25 17:10 UTC
We experienced an issue with spring-retry and spring cloud ribbon. When we try to execute a rest call through feign and ribbon to a host having the name `stateless_proxy_severs` spring will throw a NPE. However, it works fine if we replace the underscores with hyphens.

The exception is in the attached log.

[spring-retry-npe.log](https://github.com/spring-projects/spring-retry/files/1756495/spring-retry-npe.log)

**Comment by mariusneo** [comment] 2019-04-12 08:55
@bijanfahimi  i just had a look over the issue that you've mentioned, but now (a year later) spring-retry RetryTemplate class code has been changed and doesn't fit anymore to the stack trace you have reported.

Would it make sense to close the issue or does it still occur as well with 1.2.4.RELEASE ?

**Comment by bijanfahimi** [comment] 2019-04-16 07:23
@mariusneo Unfortunately, we have changed all of our hostnames. So I cannot test it anymore without putting a great amount of effort into it. You can close it if you like or maybe a regression test could test if underscores are still an issue.

**Comment by mariusneo** [comment] 2019-04-16 11:31
@bijanfahimi  i am just a github user (same as you :) ) for this project.
I was just curious what your problem was because I was just browsing through the existing spring-retry issues.

In this case I'd recommend simply closing the issue yourself.

**Comment by artembilan** [comment] 2023-12-14 23:35
I don't believe this issue has had anything to do with Spring Retry from the beginning, but since we cannot reproduce it anyway, closing as `Invalid`.

**Closed by artembilan** 2023-12-14 23:35 UTC
