### ISSUE TITLE
A little idea about result filtering

### ISSUE THREAD

**Issue by nnnnnnnextday** [spring-projects/spring-retry#416] opened 2023-12-16 09:15 UTC
At work, I often get downstream data through remote calls. 

But in case I obtain data asynchronously, it won't throw a RunTimeException but just return null result。And The retry ability will not take effect。

So I did a little attempt, Main is added a RefuseNullResultRetryPolicy and added a judge logic in RetryTemplate.doExecute method.

if I choose this RetryPolicy and get null result. It will throw a exception and then retry.

I think this can be extended further which means that we can do some extra work on executing normal processes.

![WechatIMG49](https://github.com/spring-projects/spring-retry/assets/56545124/c7f91f2f-56ac-4190-b04f-3020f33e44de)
![WechatIMG50](https://github.com/spring-projects/spring-retry/assets/56545124/cc4e9747-5a46-40e7-9e60-bf0727b229d9)
![WechatIMG51](https://github.com/spring-projects/spring-retry/assets/56545124/399eca65-e61f-41de-8533-e5c85fdc9c65)

**Comment by artembilan** [comment] 2023-12-21 16:58
> But in case I obtain data asynchronously, it won't throw a RunTimeException but just return null result

Doesn't sound like a `RetryTemplate` responsibility.
Now imaging the logic where no `RetryTemplate`.
For consistency the output must be exactly same.
So, if you return null, but not throw an exception, then there is nothing what `RetryTemplate` must do.
The `null` result is not a part of retry pattern at all. 
It is just another normal result: https://java-design-patterns.com/patterns/retry/

So, consider to fix that call to throw an exception in case of null result, but don't try to push a decision down to the `RetryTemplate`.

At the same time we have already a specific generic hook to react to the result:
```
					T result = retryCallback.doWithRetry(context);
					doOnSuccessInterceptors(retryCallback, context, result);
					return result;
```
So, you can register a `RetryListener` and throw desired exception from its `onSuccess()` impl when `result` argument is `null`.

Not sure, though, why we don't see that `doOnSuccessInterceptors()` call on your screenshot, but I'm closing this as `Works as Designed` since we already have a solution you are looking for, even if I find the problem as made-up.

**Closed by artembilan** 2023-12-21 16:58 UTC
