### ISSUE TITLE
Spring retry XML equivalent to @EnableRetry

### ISSUE THREAD

**Issue by manojkr001** [spring-projects/spring-retry#191] opened 2020-01-14 10:11 UTC
Spring retry XML equivalent to @EnableRetry

**Comment by dsyer** [comment] 2020-01-20 11:33
I guess you need to create a bean of type `RetryConfiguration` (and enable annotation processing). It's a long time since anyone even thought of trying it. Does that work for you?

**Comment by artembilan** [comment] 2024-09-12 16:47
Duplicate of #148

**Closed by artembilan** 2024-09-12 16:47 UTC
