### ISSUE TITLE
@Retryable on interface instead of implementation class

### ISSUE THREAD

**Issue by altfatterz** [spring-projects/spring-retry#32] opened 2015-08-31 12:25 UTC
I had to put the `@Retryable` on the interface method instead of the implementation class in order to make it work, which is different how it is described in the documentation. 

```
public interface DemoService {
    @Retryable(RemoteAccessException.class)
    void service();
}
```

**Comment by kimsaabyepedersen** [comment] 2016-02-10 15:09
I have the same. This is bit odd and the only place we use annotations on interfaces.

**Comment by garyrussell** [comment] 2016-02-10 23:02
Confirmed; the `AnnotationAwareRetryOperationsInterceptor` does not unwrap the proxy to see if the target is annotated if it finds no annotation on the interface.

**Comment by conivek** [comment] 2016-03-22 19:59
I'm just starting to use Spring Retry, and I ran into this as well. I'm looking forward to seeing this fix released.

**Comment by wimdeblauwe** [comment] 2016-04-26 12:55
I tried Spring Retry for the first time and after seeing that `@Retryable` was not working, I use the template, but probably this was also the reason for it not working.

**Comment by DieterVDW** [comment] 2016-07-15 14:39
Same for me: tried this and did not get it working. Almost made me dump the solution.

This should be fixed ASAP, incredibly confusing!

**Comment by rLitto** [comment] 2016-07-22 08:59
I see there are at least two pull requests to fix this problem. Are they going to be merged? Why the new release did not include them?

**Closed** 2016-08-23 09:56 UTC

**Comment by nodje** [comment] 2016-09-20 07:37
Glad this has been fixed.
Any time frame for the next release including the fix?

**Comment by dsyer** [comment] 2016-09-20 08:29
I was thinking about 1.2.0 for Spring Boot 1.5.0 (so 2016 probably). If you need this change urgently I suppose we could cherry pick it for 1.1.4.

**Comment by nodje** [comment] 2016-09-20 09:56
It works with the annotation on the interface so it's no hurry really.
I'm just eager to clean my code but it's really your choice of course.

On the other hand I guess the earlier you provide a bug fix the better it is for the community. It took me a while to figure this was the reason why I couldn't get spring-retry to work, so I suppose it would allow others to save some time.

**Comment by wimdeblauwe** [comment] 2016-09-20 11:53
+1 for a bugfix release so this can also be used for the next Spring Boot 1.4.x release.

**Comment by wimdeblauwe** [comment] 2016-09-21 12:21
For those that use Spring boot, the just released 1.4.1 contains Spring Retry 1.1.4 and thus this fix. See https://github.com/spring-projects/spring-boot/issues/6960. Thanks to all involved in making it happen!

**Comment by karthikitzmi** [comment] 2016-10-27 21:58
@EnableRetry
@Configuration
public class App {	
	public static void main(String[] args) throws Exception {
		parentservice p = new  SpringRetryWithHystrixService();
		String status = p.getStatus();
		System.out.println(status);
	}
}

public class SpringRetryWithHystrixService implements parentservice{
	
	public static int i=0;
	
	public String getStatus() throws Exception{
		System.out.println(i++);
		throw new NullPointerException();
	}
	
	@Recover
	public static String getRecoveryStatus(){
		return new CommandHelloWorld().execute();
	}
}

public interface parentservice {
	@Retryable(maxattempts=5)
	String getStatus() throws Exception;
}

This just throws NullpointerException at first attempt and exits. Having annotation on interface doesn't work as well.

**Comment by dsyer** [comment] 2016-10-28 06:26
@karthikitzmi there are quite a few reasons why that won't work, and this issue is closed. Maybe try stackoverflow?
