### ISSUE TITLE
RetryTemplate with TimeoutRetryPolicy does not execute first attempt

### ISSUE THREAD

**Issue by moaxcp** [spring-projects/spring-retry#189] opened 2019-11-14 18:17 UTC
Hello, I just started diving into spring-retry and it is awesome I found some unexpected behavior that might not be a real problem but I wanted to share it anyway. I have a `RetryTemplate` with a `TimeoutRetryPolicy` and `BackoffPolicy`. When I set both policies to 1 millis the operation sometimes doesn't execute. I see in the javadoc that the timer starts when `open` is called but I'm wondering when the check happens. I am setting these to 1 millis for unit tests so I know the operation happens at least one time. It seems that the operation should always happen at least one time before timing out. Either way thanks for the great library!

**Comment by artembilan** [comment] 2019-11-14 18:22
May we have some code to play with and possibly reproduce?

Thanks

**Comment by moaxcp** [comment] 2019-11-14 18:34
It looks like the policy is checked before the operation. Looking at the code in RetryTemplate there is:

```
while (canRetry(retryPolicy, context) && !context.isExhaustedOnly()) {
    ...
}
```

And `canRetry` in `TimeoutRetryPolicy` may return false at that point. I'm not sure it is possible to fix this but it is interesting to observe that a RetryPolicy can turn off operations altogether.

**Comment by artembilan** [comment] 2019-11-14 18:45
Well, that's correct and fully expected according the logic:
```
public boolean isAlive() {
	return (System.currentTimeMillis() - start) <= timeout;
}
```

So, if the start of the operation and first attempt to retry takes more time than `timeout`, we're done and it is not going to retry at all.
We could adjust a logic over there somehow, but on the other hand we should treat it as a feature, because according retry contract we always check for "can" even on first try:
```
		/*
			 * We allow the whole loop to be skipped if the policy or context already
			 * forbid the first try. This is used in the case of external retry to allow a
			 * recovery in handleRetryExhausted without the callback processing (which
			 * would throw an exception).
			 */
			while (canRetry(retryPolicy, context) && !context.isExhaustedOnly()) {

```

**Comment by moaxcp** [comment] 2020-02-09 17:37
I just wanted to follow up on this before I forget. Having this in a RetryPolicy is helpful when the application just wants operations to stop. What I did to change this behavior for my use case was to extend the TimeoutPolicy and check for at least one retry before using the normal check.

```
TimeoutRetryPolicy timeoutPolicy = new TimeoutRetryPolicy() {
    public boolean canRetry(RetryContext context) {
        if(context.getRetryCount() > 1) {
            return super.canRetry(context);
        } else {
            return true;
        }
    }
}
```

This way we are able to ensure an operation happens at least once before checking for a timeout.

**Comment by artembilan** [comment] 2020-02-10 15:46
Good. So, closing as "Works as Desiged".

Anything else is already out of this issue scope.

**Closed by artembilan** 2020-02-10 15:46 UTC
